[workspace]
resolver = "2"
members = [
  "crates/cove-diag",
  "crates/cove-schema",
  "crates/cove-syntax",
  "crates/cove-sema",
  "crates/cove-ir",
  "crates/cove-runtime",
  "crates/cove-cli",
  "crates/cove-bench",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/myuon/cove"

[workspace.dependencies]
cove-diag = { path = "crates/cove-diag" }
cove-schema = { path = "crates/cove-schema" }
cove-syntax = { path = "crates/cove-syntax" }
cove-sema = { path = "crates/cove-sema" }
cove-ir = { path = "crates/cove-ir" }
cove-runtime = { path = "crates/cove-runtime" }
