//! The generator for `std.string`'s case-mapping tables, and the assertion
//! that what is checked in is what it generates.
//!
//! [ADR 0064](../../../docs/adr/0064-an-intrinsic-names-a-machine-not-a-method.md)'s
//! Decision 5 is that **Cove owns its Unicode version**, and that the tables
//! it owns are "generated by a checked-in generator, committed as a
//! reproducible asset, with a test asserting regeneration is byte-identical".
//! This file is all three. It builds the six tables from the toolchain's own
//! `char::to_uppercase` and `char::to_lowercase` and from the observable
//! behaviour of its `Final_Sigma`, and compares them against the literals in
//! `std/string.cove`.
//!
//! So a toolchain whose Unicode tables differ from Unicode 17.0.0 is a
//! **failing test naming the table**, rather than a silent change to what
//! every Cove program means. That is the whole of the point: until
//! `String.toUpper` moved, the mapping was `str::to_uppercase` and the version
//! was whatever the Rust toolchain happened to be built against, recorded
//! nowhere.
//!
//! # Regenerating
//!
//! ```console
//! $ COVE_WRITE_CASE_TABLES=1 cargo test -p cove-sema --profile checked \
//!     --test unicase -- --ignored regenerates
//! ```
//!
//! That rewrites `crates/cove-sema/std/string.cove` in place, replacing the
//! six literals and touching nothing else. Without the environment variable it
//! does nothing, so `cargo ratchet` — which runs every `#[ignore]`d test in
//! the workspace — cannot write into the source tree.
//!
//! # Why the sigma's two sets are derived by probing
//!
//! Four of the six tables come from `char::to_uppercase` and
//! `char::to_lowercase`, which are the mappings themselves. The other two are
//! Unicode's `Cased` and `Case_Ignorable`, and `char` exposes neither. They
//! are recovered from the only place this toolchain answers about them: the
//! `Final_Sigma` rule inside `str::to_lowercase`. `X` followed by `Σ`
//! lowercases to a *final* sigma exactly when `X` satisfies the rule's Before
//! condition, which is what being cased means there; and `Α` `X` `Σ` does so
//! for a character that is skipped, which is what being ignorable means.
//!
//! That recovers the sets **as the rule uses them**, which is not quite the
//! two published sets: 268 code points are in both of Unicode's, and the scan
//! skips before it asks, so each of those counts as ignorable. The tables here
//! are therefore `Cased` *minus* `Case_Ignorable`, and `Case_Ignorable`. Both
//! were reconciled against Unicode 17.0.0's `DerivedCoreProperties.txt` when
//! they were first written: 4,632 published `Cased` less the 268, and 2,794
//! `Case_Ignorable` to the code point.

use std::collections::BTreeSet;
use std::path::PathBuf;

/// `U+03A3` GREEK CAPITAL LETTER SIGMA.
const SIGMA: char = '\u{03A3}';
/// `U+03C2` GREEK SMALL LETTER FINAL SIGMA.
const FINAL: char = '\u{03C2}';
/// `U+0391` GREEK CAPITAL LETTER ALPHA — a cased character to stand in front
/// of a sigma, so that the Before condition is satisfied by something other
/// than the character under test.
const ALPHA: char = '\u{0391}';

/// The six table functions, in the order they appear in `std/string.cove`.
const NAMES: [&str; 6] = [
    "upperRuns",
    "lowerRuns",
    "upperExpansions",
    "lowerExpansions",
    "casedRanges",
    "ignorableRanges",
];

/// `value` as `width` base-32 symbols over the alphabet `0` (48) through `O`
/// (79).
///
/// A contiguous run, so a reader decodes a symbol by subtracting 48 rather
/// than by looking it up, and one that contains none of `"`, `\`, `{` and `}`
/// — so a table is an ordinary Cove string literal with no escape in it. There
/// is no window of 64 contiguous printable bytes that misses the backslash,
/// which is why this is 32 and not 64.
fn symbols(mut value: u32, width: usize) -> String {
    let mut out = vec![0u8; width];
    for at in (0..width).rev() {
        out[at] = 48 + (value % 32) as u8;
        value /= 32;
    }
    assert_eq!(value, 0, "a value does not fit in {width} symbols");
    String::from_utf8(out).expect("the alphabet is ASCII")
}

/// One direction's run table and expansion text.
struct Direction {
    runs: String,
    expansions: String,
}

/// Builds a direction's tables out of the toolchain's per-character mapping.
///
/// A record is thirteen symbols: the first code point of a run (five), how
/// many code points it covers (two), the stride (one), the kind (one) and a
/// payload (four). A run is a maximal stretch of code points with the *same*
/// answer — the same delta, or the same slice of the expansion text — at a
/// stride of one or two. Two, because the Latin Extended-A pattern puts a
/// capital and its small letter next to each other, so every *other* code
/// point shares a delta; allowing it takes the uppercase table from 688
/// records to 302.
fn direction(upper: bool) -> Direction {
    let mut expansions = String::new();
    let mut entries: Vec<(u32, u8, u64)> = Vec::new();
    for point in 0u32..=0x10FFFF {
        let Some(character) = char::from_u32(point) else {
            continue;
        };
        let mapped: String = if upper {
            character.to_uppercase().collect()
        } else {
            character.to_lowercase().collect()
        };
        if mapped == character.to_string() {
            continue;
        }
        if mapped.chars().count() == 1 {
            let delta = mapped.chars().next().expect("one character") as i64 - point as i64;
            entries.push((point, 0, (delta + 524_288) as u64));
        } else {
            // An answer already inside the text is not written again: `FF` is
            // inside `FFI`, and 102 expansions share 317 bytes.
            let at = match expansions.find(&mapped) {
                Some(at) => at,
                None => {
                    let at = expansions.len();
                    expansions.push_str(&mapped);
                    at
                }
            };
            assert!(mapped.len() <= 15, "an expansion is longer than a nibble");
            entries.push((point, 1, at as u64 * 16 + mapped.len() as u64));
        }
    }

    let mut runs: Vec<(u32, u32, u32, u8, u64)> = Vec::new();
    let mut at = 0;
    while at < entries.len() {
        let (point, kind, payload) = entries[at];
        let mut best = (1usize, 1u32);
        for stride in [1u32, 2u32] {
            let mut count = 1usize;
            while at + count < entries.len()
                && entries[at + count].1 == kind
                && entries[at + count].2 == payload
                && entries[at + count].0 == point + stride * count as u32
            {
                count += 1;
            }
            if count > best.0 {
                best = (count, stride);
            }
        }
        runs.push((point, best.0 as u32, best.1, kind, payload));
        at += best.0;
    }

    // A stride-two run must not reach over a code point another record starts
    // at, because "the last record starting at or below `point`" is how the
    // binary search in `std.string` decides which record can hold a code
    // point. Nothing in Unicode 17.0.0 produces one; this shortens any run
    // that does rather than trusting that nothing ever will.
    while let Some(over) = (0..runs.len().saturating_sub(1)).find(|at| {
        let (start, count, stride, _, _) = runs[*at];
        runs[at + 1].0 <= start + (count - 1) * stride
    }) {
        let (start, count, stride, kind, payload) = runs[over];
        let next = runs[over + 1].0;
        let mut shorter = count;
        while shorter > 1 && start + (shorter - 1) * stride >= next {
            shorter -= 1;
        }
        runs[over] = (start, shorter, stride, kind, payload);
        let split: Vec<_> = (shorter..count)
            .map(|nth| (start + nth * stride, 1u32, 1u32, kind, payload))
            .collect();
        for (nth, record) in split.into_iter().enumerate() {
            runs.insert(over + 1 + nth, record);
        }
    }
    for at in 0..runs.len().saturating_sub(1) {
        let (start, count, stride, _, _) = runs[at];
        assert!(
            start + (count - 1) * stride < runs[at + 1].0,
            "two records hold the same code point"
        );
    }

    let mut packed = String::new();
    for (start, count, stride, kind, payload) in &runs {
        packed.push_str(&symbols(*start, 5));
        packed.push_str(&symbols(*count, 2));
        packed.push_str(&symbols(*stride, 1));
        packed.push_str(&symbols(*kind as u32, 1));
        packed.push_str(&symbols(*payload as u32, 4));
    }
    Direction {
        runs: packed,
        expansions,
    }
}

/// `Cased` less `Case_Ignorable`, and `Case_Ignorable`, as this toolchain's
/// `Final_Sigma` uses them.
fn sigma_sets() -> (BTreeSet<u32>, BTreeSet<u32>) {
    let mut cased = BTreeSet::new();
    let mut ignorable = BTreeSet::new();
    for point in 0u32..=0x10FFFF {
        let Some(character) = char::from_u32(point) else {
            continue;
        };
        // `X Σ`: the sigma is final exactly when `X` satisfies the Before
        // condition on its own, which is what the rule means by cased.
        if format!("{character}{SIGMA}")
            .to_lowercase()
            .ends_with(FINAL)
        {
            cased.insert(point);
            continue;
        }
        // `Α X Σ`: final only if `X` was stepped over.
        if format!("{ALPHA}{character}{SIGMA}")
            .to_lowercase()
            .ends_with(FINAL)
        {
            ignorable.insert(point);
        }
    }
    (cased, ignorable)
}

/// A set as seven-symbol records: a first code point in five and a count in
/// two.
fn ranges(set: &BTreeSet<u32>) -> String {
    let points: Vec<u32> = set.iter().copied().collect();
    let mut packed = String::new();
    let mut at = 0;
    while at < points.len() {
        let mut end = at + 1;
        // 1023 is what two symbols hold.
        while end < points.len() && points[end] == points[at] + (end - at) as u32 && end - at < 1023
        {
            end += 1;
        }
        packed.push_str(&symbols(points[at], 5));
        packed.push_str(&symbols((end - at) as u32, 2));
        at = end;
    }
    packed
}

/// All six tables, in [`NAMES`] order.
fn generate() -> Vec<String> {
    let upper = direction(true);
    let lower = direction(false);
    let (cased, ignorable) = sigma_sets();
    assert!(
        cased.contains(&(SIGMA as u32)),
        "a sigma is cased, so `ΣΣ` lowercases to `σς`"
    );
    vec![
        upper.runs,
        lower.runs,
        upper.expansions,
        lower.expansions,
        ranges(&cased),
        ranges(&ignorable),
    ]
}

/// Where the standard library's `String` module lives.
fn source_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("std/string.cove")
}

/// The literal each table function answers, in [`NAMES`] order.
///
/// A table function is `fn <name>() -> String {`, one line holding the literal,
/// and `}` — which is what the generator writes and what the formatter leaves
/// alone, so finding it is a line lookup rather than a parse.
fn checked_in(source: &str) -> Vec<String> {
    NAMES
        .iter()
        .map(|name| {
            let head = format!("fn {name}() -> String {{\n");
            let at = source
                .find(&head)
                .unwrap_or_else(|| panic!("`std/string.cove` has no `fn {name}() -> String`"));
            let rest = &source[at + head.len()..];
            let line = rest.lines().next().expect("a line holding the literal");
            let inside = line
                .trim_start()
                .strip_prefix('"')
                .and_then(|held| held.strip_suffix('"'))
                .unwrap_or_else(|| panic!("`{name}`'s body is not one string literal: `{line}`"));
            inside.to_string()
        })
        .collect()
}

/// `source` with each table function's literal replaced.
fn rewritten(source: &str, tables: &[String]) -> String {
    let mut out = source.to_string();
    for (name, table) in NAMES.iter().zip(tables) {
        let head = format!("fn {name}() -> String {{\n");
        let at = out.find(&head).expect("the function is there") + head.len();
        let end = at + out[at..].find('\n').expect("a line");
        out.replace_range(at..end, &format!("  \"{table}\""));
    }
    out
}

#[test]
fn the_case_tables_are_this_toolchains_unicode() {
    let generated = generate();
    let source = std::fs::read_to_string(source_path()).expect("`std/string.cove` reads");
    let held = checked_in(&source);
    let version = char::UNICODE_VERSION;
    for (at, name) in NAMES.iter().enumerate() {
        assert_eq!(
            held[at], generated[at],
            "`std.string.{name}` is not what this toolchain's Unicode tables generate. \
             The toolchain is Unicode {}.{}.{}, and `crates/cove-sema/std/string.cove` \
             records the version its tables are drawn from — both the literal and that \
             sentence have to move together. \
             `COVE_WRITE_CASE_TABLES=1 cargo test -p cove-sema --profile checked \
             --test unicase -- --ignored regenerates` rewrites the file.",
            version.0, version.1, version.2,
        );
    }
}

/// What the six tables *are*, asserted as written-down numbers.
///
/// Beside the comparison above, so that a change which regenerated the tables
/// and moved the expectation at once still has to move a figure a reader can
/// check against the prose in `std/string.cove` — which quotes every one of
/// these.
#[test]
fn the_tables_are_the_size_the_standard_library_says_they_are() {
    let generated = generate();
    assert_eq!(generated[0].len(), 3926, "`upperRuns` is 302 records");
    assert_eq!(generated[0].len() % 13, 0, "`upperRuns` is whole records");
    assert_eq!(generated[1].len(), 2418, "`lowerRuns` is 186 records");
    assert_eq!(generated[1].len() % 13, 0, "`lowerRuns` is whole records");
    assert_eq!(generated[2].len(), 317, "`upperExpansions` is 317 bytes");
    assert_eq!(
        generated[3], "i\u{0307}",
        "`U+0130` is the only code point whose lowercase mapping is more than one character"
    );
    assert_eq!(generated[4].len(), 1057, "`casedRanges` is 151 records");
    assert_eq!(generated[5].len(), 3248, "`ignorableRanges` is 464 records");
    let total: usize = generated.iter().map(|table| table.len()).sum();
    assert_eq!(total, 10969, "the whole asset is 10,969 bytes");
    for (name, table) in NAMES.iter().zip(&generated) {
        for bad in ['"', '\\', '{', '}'] {
            assert!(
                !table.contains(bad),
                "`{name}` holds `{bad}`, which a Cove string literal would have to escape"
            );
        }
    }
}

/// Rewrites `std/string.cove`'s six literals.
///
/// `#[ignore]`d, so `cargo t` does not run it, and gated on
/// `COVE_WRITE_CASE_TABLES` so that `cargo ratchet` — which runs every ignored
/// test in the workspace — cannot write into the source tree either. What
/// makes a drift *visible* is the comparison above; this is only how it is
/// repaired.
#[test]
#[ignore = "writes into the source tree; set COVE_WRITE_CASE_TABLES=1"]
fn regenerates_the_case_tables() {
    if std::env::var_os("COVE_WRITE_CASE_TABLES").is_none() {
        eprintln!(
            "set COVE_WRITE_CASE_TABLES=1 to rewrite {}",
            source_path().display()
        );
        return;
    }
    let path = source_path();
    let source = std::fs::read_to_string(&path).expect("`std/string.cove` reads");
    let out = rewritten(&source, &generate());
    std::fs::write(&path, out).expect("`std/string.cove` writes");
    eprintln!("rewrote {}", path.display());
}
