//! `cove reference`: the builtin and Host API reference, generated.
//!
//! Every name the language answers to is declared once, in
//! `cove_schema`: [`cove_schema::builtins::BUILTINS`] and
//! [`cove_schema::builtins::FREE_BUILTINS`] for the builtins, and
//! [`cove_schema::hosts::SHIPPED`] for the Host API. The checker reads those
//! tables, both evaluators read them, and every diagnostic that lists what a
//! type can do reads them. This command reads the same tables and writes them
//! out for people and for tools.
//!
//! It is generated rather than written because a hand-kept list of a hundred
//! and fifty signatures is a list that is wrong within a week, and because
//! the interesting question about a builtin — whether it has to be one — can
//! only be argued from a complete inventory. `--check` is what keeps the
//! committed copy honest; CI runs it.
//!
//! Two outputs from one walk:
//!
//! - **Markdown**, for a person. Grouped by type, with the cases, fields,
//!   associated functions and methods each type declares, and the Host API
//!   beside them so the boundary between "the language does this" and "a host
//!   does this" is one document rather than two.
//! - **JSON**, for everything else: the browser playground's completion, an
//!   editor, a manifest an assistant reads. It carries the same facts in the
//!   same order, so a tool never has to parse the prose.
//!
//! # What this is not
//!
//! It is not a specification. `docs/LANGUAGE_REFERENCE.md` says what a form
//! *means* and is held to the implementation by
//! `crates/cove-runtime/tests/conformance.rs`; this says what exists. A
//! signature here promises that the checker will accept a call of that shape,
//! and nothing about what the call does.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use cove_schema::builtins::{
    builtins, free_builtins, BuiltinSchema, FreeBuiltinKind, FreeBuiltinSchema, MethodSchema,
};
use cove_schema::hosts::shipped;
use cove_schema::{Effect, ModuleSchema};

use crate::CliError;

/// Where the Markdown goes unless `--out-md` names somewhere else.
const DEFAULT_MARKDOWN: &str = "docs/BUILTINS.md";
/// Where the JSON goes unless `--out-json` names somewhere else.
const DEFAULT_JSON: &str = "docs/builtins.json";

/// The version of the JSON's own shape, so a consumer can refuse a document
/// it does not understand rather than misread one.
const JSON_FORMAT: u32 = 1;

const PREAMBLE: &str = "\
<!-- Generated by `cove reference`. Do not edit by hand.

     Every entry below is read out of `crates/cove-schema`, which is the one
     table the checker, both evaluators, and every diagnostic that lists what
     a type can do already read. Regenerate with `cove reference`; CI runs
     `cove reference --check` and fails if this file is stale. -->
";

/// `cove reference [--check] [--out-md <path>] [--out-json <path>]`.
pub(crate) fn cmd_reference(args: &[String]) -> Result<(), CliError> {
    let mut check = false;
    let mut markdown = PathBuf::from(DEFAULT_MARKDOWN);
    let mut json = PathBuf::from(DEFAULT_JSON);
    let mut at = 0;
    while at < args.len() {
        match args[at].as_str() {
            "--check" => check = true,
            "--out-md" => {
                at += 1;
                markdown = PathBuf::from(
                    args.get(at)
                        .ok_or_else(|| CliError::Message("`--out-md` needs a path".to_string()))?,
                );
            }
            "--out-json" => {
                at += 1;
                json =
                    PathBuf::from(args.get(at).ok_or_else(|| {
                        CliError::Message("`--out-json` needs a path".to_string())
                    })?);
            }
            other => {
                return Err(CliError::Message(format!(
                    "unknown option `{other}` for `cove reference`"
                )))
            }
        }
        at += 1;
    }

    let rendered_markdown = render_markdown();
    let rendered_json = render_json();

    if check {
        let mut stale = Vec::new();
        for (path, want) in [(&markdown, &rendered_markdown), (&json, &rendered_json)] {
            match std::fs::read_to_string(path) {
                Ok(found) if found == *want => {}
                _ => stale.push(path.display().to_string()),
            }
        }
        if stale.is_empty() {
            println!("reference is current");
            return Ok(());
        }
        return Err(CliError::Message(format!(
            "{} is stale; run `cove reference`",
            stale.join(" and ")
        )));
    }

    write(&markdown, &rendered_markdown)?;
    write(&json, &rendered_json)?;
    println!("wrote {} and {}", markdown.display(), json.display());
    Ok(())
}

fn write(path: &Path, body: &str) -> Result<(), CliError> {
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent).map_err(|e| {
                CliError::Message(format!("cannot create {}: {e}", parent.display()))
            })?;
        }
    }
    std::fs::write(path, body)
        .map_err(|e| CliError::Message(format!("cannot write {}: {e}", path.display())))
}

// ------------------------------------------------------------------ markdown

fn render_markdown() -> String {
    let mut out = String::with_capacity(48 * 1024);
    out.push_str(PREAMBLE);
    out.push_str("\n# Builtins and the Host API\n\n");
    out.push_str(
        "What the language answers to, and what a host answers to. Two tables, and the\n\
         line between them is the whole of what Cove can do without being given\n\
         anything: a **builtin** is the language's own, evaluated in the process with no\n\
         capability asked for; a **Host operation** reaches outside it and is refused\n\
         unless the run was granted the capability it names.\n\n",
    );

    let types = builtins();
    let free = free_builtins();
    let modules = shipped();
    let methods: usize = types.iter().map(|t| t.methods.len()).sum();
    let associated: usize = types.iter().map(|t| t.associated.len()).sum();
    let operations: usize = modules.iter().map(|m| m.operations.len()).sum();
    let _ = write!(
        out,
        "| | |\n| --- | --- |\n| builtin types | {} |\n| builtin methods | {} |\n\
         | builtin associated functions | {} |\n| free builtins | {} |\n\
         | host modules | {} |\n| host operations | {} |\n\n",
        types.len(),
        methods,
        associated,
        free.len(),
        modules.len(),
        operations,
    );

    out.push_str("## Free builtins\n\n");
    out.push_str(
        "Called on nothing, the way a declared function is. Every one of them binds its\n\
         own type parameters, because there is no receiver to read one off.\n\n",
    );
    out.push_str("| name | kind | signature |\n| --- | --- | --- |\n");
    for entry in free {
        let _ = writeln!(
            out,
            "| `{}` | {} | `{}` |",
            entry.name,
            free_kind(entry),
            entry.signature()
        );
    }
    out.push('\n');

    out.push_str("## Builtin types\n\n");
    for schema in types {
        render_type(&mut out, schema);
    }

    out.push_str("## Host API\n\n");
    out.push_str(
        "Not builtins. Every operation below names a capability, is refused when the run\n\
         was not granted it, is charged against the run's Host-call budget, and appears\n\
         in a trace. A builtin does none of those things.\n\n",
    );
    for module in modules {
        render_module(&mut out, module);
    }
    out
}

fn free_kind(entry: &FreeBuiltinSchema) -> &'static str {
    match entry.kind {
        FreeBuiltinKind::Constructor => "constructor",
        FreeBuiltinKind::Assertion => "assertion",
    }
}

fn render_type(out: &mut String, schema: &BuiltinSchema) {
    let _ = writeln!(out, "### `{}`\n", type_header(schema));
    let mut notes = Vec::new();
    if schema.namespace {
        notes.push("written as a namespace".to_string());
    } else {
        notes.push("never written by name".to_string());
    }
    if !schema.parameters.is_empty() {
        notes.push(format!(
            "binds {}",
            schema
                .parameters
                .iter()
                .map(|p| format!("`{p}`"))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    let _ = writeln!(out, "{}.\n", notes.join("; "));

    if !schema.cases.is_empty() {
        out.push_str("**Cases.** ");
        let cases: Vec<String> = schema
            .cases
            .iter()
            .map(|case| format!("`{}`", case.signature()))
            .collect();
        let _ = writeln!(out, "{}\n", cases.join(", "));
    }
    if !schema.fields.is_empty() {
        out.push_str("**Fields.** ");
        let fields: Vec<String> = schema
            .fields
            .iter()
            .map(|field| format!("`{}: {}`", field.name, field.ty))
            .collect();
        let _ = writeln!(out, "{}\n", fields.join(", "));
    }
    if !schema.associated.is_empty() {
        let _ = writeln!(out, "**Associated functions.**\n");
        render_methods(out, schema.name, schema.associated, false);
    }
    if !schema.methods.is_empty() {
        let _ = writeln!(out, "**Methods.**\n");
        render_methods(out, schema.name, schema.methods, true);
    }
}

fn type_header(schema: &BuiltinSchema) -> String {
    if schema.parameters.is_empty() {
        return schema.name.to_string();
    }
    format!("{}<{}>", schema.name, schema.parameters.join(", "))
}

fn render_methods(out: &mut String, owner: &str, entries: &[MethodSchema], receiver: bool) {
    out.push_str("| signature | ");
    if receiver {
        out.push_str("`var self` | ");
    }
    out.push_str("variadic | binds | implemented by |\n| --- | ");
    if receiver {
        out.push_str("--- | ");
    }
    out.push_str("--- | --- | --- |\n");
    for entry in entries {
        let binds = if entry.generics.is_empty() {
            String::new()
        } else {
            entry
                .generics
                .iter()
                .map(|g| format!("`{g}`"))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = write!(out, "| `{}` | ", entry.signature());
        if receiver {
            let _ = write!(out, "{} | ", yes_no(entry.mutating));
        }
        let _ = writeln!(
            out,
            "{} | {binds} | `{}` |",
            yes_no(entry.variadic),
            implemented_by(owner, entry.name, receiver)
        );
    }
    out.push('\n');
}

/// Where a builtin method or associated function's body lives: `machine`
/// for the ordinary case, or the standard-library function it names.
///
/// This is the same fact `cove_ir`'s lowering reads before it dispatches a
/// call per receiver type — `cove_schema::builtins::standard_binding` and
/// `standard_associated_binding` — so the generated reference and the
/// lowering can never disagree about which methods these are.
///
/// `receiver` is which of the two tables to ask, exactly as it is at both
/// call sites above: a builtin type can bind a method and an associated
/// function of the same name to two different standard-library functions —
/// `Duration`'s `millis` is the reader `std.duration.millis` as a method and
/// the builder `std.duration.ofMillis` as an associated function — so
/// asking the wrong table would either miss the binding or report the
/// other one's.
fn implemented_by(owner: &str, method: &str, receiver: bool) -> String {
    let binding = if receiver {
        cove_schema::builtins::standard_binding(owner, method)
    } else {
        cove_schema::builtins::standard_associated_binding(owner, method)
    };
    match binding {
        Some(binding) => format!("{}.{}", binding.module, binding.function),
        None => "machine".to_string(),
    }
}

fn yes_no(flag: bool) -> &'static str {
    if flag {
        "yes"
    } else {
        ""
    }
}

fn render_module(out: &mut String, module: &ModuleSchema) {
    let _ = writeln!(
        out,
        "### `{}`\n\nCapability `{}`.\n",
        module.name, module.capability
    );
    if !module.operations.is_empty() {
        out.push_str(
            "| operation | capability | effect | cancellable |\n| --- | --- | --- | --- |\n",
        );
        for op in module.operations {
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | {} |",
                op.signature(),
                op.capability,
                effect_name(op.effect),
                yes_no(op.cancellable)
            );
        }
        out.push('\n');
    }
    for ty in module.types {
        let _ = writeln!(
            out,
            "- type `{}.{}` — `{}`",
            module.name,
            ty.name,
            ty.initializer()
        );
    }
    for resource in module.resources {
        let _ = writeln!(
            out,
            "- resource `{}.{}` — {}",
            module.name,
            resource.name,
            if resource.task_safe {
                "may cross a task boundary"
            } else {
                "may not cross a task boundary"
            }
        );
    }
    if !module.types.is_empty() || !module.resources.is_empty() {
        out.push('\n');
    }
}

fn effect_name(effect: Effect) -> &'static str {
    match effect {
        Effect::Read => "read",
        Effect::ReversibleWrite => "reversible write",
        Effect::IrreversibleWrite => "irreversible write",
    }
}

// ---------------------------------------------------------------------- json

/// The same inventory, for a consumer that is not a person.
///
/// Hand-written rather than derived, for the reason everything in this
/// workspace is: the shape is small, fixed, and has exactly one producer.
/// Adding a serialisation crate to emit six object kinds would be a larger
/// dependency than the thing it emits.
///
/// The order is the schema's own order everywhere, because that order is
/// already meaningful — it is what a diagnostic reads out when it has to list
/// what a type can do — and because a stable order is what makes the
/// committed file diffable.
fn render_json() -> String {
    let mut out = String::with_capacity(64 * 1024);
    out.push_str("{\n");
    let _ = writeln!(out, "  \"format\": {JSON_FORMAT},");
    out.push_str("  \"freeBuiltins\": [\n");
    let free = free_builtins();
    for (at, entry) in free.iter().enumerate() {
        out.push_str("    {");
        let _ = write!(
            out,
            "\"name\": {}, \"kind\": {}, \"signature\": {}, \"generics\": {}, \"params\": {}, \"result\": {}, \"host\": false",
            quote(entry.name),
            quote(free_kind(entry)),
            quote(&entry.signature()),
            string_list(entry.generics),
            params_json(entry.params),
            quote(&entry.result.to_string()),
        );
        out.push_str(if at + 1 == free.len() { "}\n" } else { "},\n" });
    }
    out.push_str("  ],\n  \"types\": [\n");
    let types = builtins();
    for (at, schema) in types.iter().enumerate() {
        out.push_str("    {\n");
        let _ = writeln!(out, "      \"name\": {},", quote(schema.name));
        let _ = writeln!(
            out,
            "      \"parameters\": {},",
            string_list(schema.parameters)
        );
        let _ = writeln!(out, "      \"namespace\": {},", schema.namespace);
        out.push_str("      \"cases\": [");
        for (i, case) in schema.cases.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            let payload: Vec<String> = case.payload.iter().map(|t| t.to_string()).collect();
            let _ = write!(
                out,
                "{{\"name\": {}, \"payload\": {}, \"signature\": {}}}",
                quote(case.name),
                string_list_owned(&payload),
                quote(&case.signature())
            );
        }
        out.push_str("],\n      \"fields\": [");
        for (i, field) in schema.fields.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            let _ = write!(
                out,
                "{{\"name\": {}, \"type\": {}}}",
                quote(field.name),
                quote(&field.ty.to_string())
            );
        }
        out.push_str("],\n      \"associated\": [\n");
        methods_json(&mut out, schema.name, schema.associated, false);
        out.push_str("      ],\n      \"methods\": [\n");
        methods_json(&mut out, schema.name, schema.methods, true);
        out.push_str("      ]\n");
        out.push_str(if at + 1 == types.len() {
            "    }\n"
        } else {
            "    },\n"
        });
    }
    out.push_str("  ],\n  \"hostModules\": [\n");
    let modules = shipped();
    for (at, module) in modules.iter().enumerate() {
        out.push_str("    {\n");
        let _ = writeln!(out, "      \"name\": {},", quote(module.name));
        let _ = writeln!(out, "      \"capability\": {},", quote(module.capability));
        out.push_str("      \"operations\": [\n");
        for (i, op) in module.operations.iter().enumerate() {
            let params: Vec<String> = op.params.iter().map(|t| t.to_string()).collect();
            let _ = write!(
                out,
                "        {{\"name\": {}, \"signature\": {}, \"params\": {}, \"variadic\": {}, \"result\": {}, \"capability\": {}, \"effect\": {}, \"cancellable\": {}, \"host\": true}}",
                quote(op.name),
                quote(&op.signature()),
                string_list_owned(&params),
                op.variadic,
                quote(&op.result.to_string()),
                quote(op.capability),
                quote(effect_name(op.effect)),
                op.cancellable,
            );
            out.push_str(if i + 1 == module.operations.len() {
                "\n"
            } else {
                ",\n"
            });
        }
        out.push_str("      ],\n      \"types\": [");
        for (i, ty) in module.types.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            let _ = write!(
                out,
                "{{\"name\": {}, \"initializer\": {}, \"isEnum\": {}}}",
                quote(ty.name),
                quote(&ty.initializer()),
                ty.is_enum()
            );
        }
        out.push_str("],\n      \"resources\": [");
        for (i, resource) in module.resources.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            let _ = write!(
                out,
                "{{\"name\": {}, \"taskSafe\": {}}}",
                quote(resource.name),
                resource.task_safe
            );
        }
        out.push_str("]\n");
        out.push_str(if at + 1 == modules.len() {
            "    }\n"
        } else {
            "    },\n"
        });
    }
    out.push_str("  ]\n}\n");
    out
}

fn methods_json(out: &mut String, owner: &str, entries: &[MethodSchema], receiver: bool) {
    for (i, entry) in entries.iter().enumerate() {
        let _ = write!(
            out,
            "        {{\"name\": {}, \"signature\": {}, \"generics\": {}, \"params\": {}, \"variadic\": {}, \"result\": {}",
            quote(entry.name),
            quote(&entry.signature()),
            string_list(entry.generics),
            params_json(entry.params),
            entry.variadic,
            quote(&entry.result.to_string()),
        );
        if receiver {
            let _ = write!(out, ", \"mutating\": {}", entry.mutating);
        }
        let _ = write!(
            out,
            ", \"implementedBy\": {}",
            quote(&implemented_by(owner, entry.name, receiver))
        );
        out.push_str(", \"host\": false}");
        out.push_str(if i + 1 == entries.len() { "\n" } else { ",\n" });
    }
}

fn params_json(params: &[cove_schema::builtins::ParamSchema]) -> String {
    let mut out = String::from("[");
    for (i, param) in params.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        let _ = write!(
            out,
            "{{\"name\": {}, \"type\": {}}}",
            quote(param.name),
            quote(&param.ty.to_string())
        );
    }
    out.push(']');
    out
}

fn string_list(items: &[&str]) -> String {
    let owned: Vec<String> = items.iter().map(|s| (*s).to_string()).collect();
    string_list_owned(&owned)
}

fn string_list_owned(items: &[String]) -> String {
    let mut out = String::from("[");
    for (i, item) in items.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&quote(item));
    }
    out.push(']');
    out
}

/// One JSON string. Every name in these tables is an identifier or a
/// signature, so a quote and a backslash is the whole of what needs escaping
/// — but it is done rather than assumed.
fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The workspace root, from the crate this test is compiled in.
    fn root() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
    }

    // The committed reference is the schema's own contents; if it can drift
    // from them it is a second table, which is the exact thing generating it
    // was for. CI runs `cove reference --check`, and this is the same
    // question asked where a contributor sees it first.
    #[test]
    fn the_committed_reference_is_what_the_schema_says() {
        for (path, want) in [
            (root().join(DEFAULT_MARKDOWN), render_markdown()),
            (root().join(DEFAULT_JSON), render_json()),
        ] {
            let found = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
            assert!(
                found == want,
                "{} is stale; run `cove reference`",
                path.display()
            );
        }
    }

    // A JSON document nothing can parse is a JSON document nobody will use,
    // and this one is written by hand — every escape and every comma is this
    // file's own. `crate::json` is the parser the playground and the trace
    // reader already go through, so it is the right one to hold it to.
    #[test]
    fn the_json_parses_and_carries_every_name_the_markdown_does() {
        let parsed = crate::json::parse(&render_json()).expect("the reference is valid JSON");
        let types = parsed
            .get("types")
            .and_then(|value| value.as_array())
            .expect("`types` is an array");
        assert_eq!(types.len(), builtins().len());
        let free = parsed
            .get("freeBuiltins")
            .and_then(|value| value.as_array())
            .expect("`freeBuiltins` is an array");
        assert_eq!(free.len(), free_builtins().len());
        let hosts = parsed
            .get("hostModules")
            .and_then(|value| value.as_array())
            .expect("`hostModules` is an array");
        assert_eq!(hosts.len(), shipped().len());

        // Every method of every type is in there, by name, with a signature.
        let mut counted = 0;
        for (schema, value) in builtins().iter().zip(types) {
            assert_eq!(
                value.get("name").and_then(|n| n.as_str()),
                Some(schema.name)
            );
            for key in ["methods", "associated"] {
                let entries = value
                    .get(key)
                    .and_then(|v| v.as_array())
                    .unwrap_or_else(|| panic!("`{key}` is an array"));
                for entry in entries {
                    assert!(entry.get("signature").and_then(|s| s.as_str()).is_some());
                    counted += 1;
                }
            }
        }
        let declared: usize = builtins()
            .iter()
            .map(|schema| schema.methods.len() + schema.associated.len())
            .sum();
        assert_eq!(counted, declared);
    }
}
